/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OpportunityDetailsRouteImport } from './routes/opportunity-details'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as PinRouteImport } from './routes/pin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RoadmapBuilderRouteImport } from './routes/roadmap-builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityDetailsRoute = OpportunityDetailsRouteImport.update({
  id: '/opportunity-details',
  path: '/opportunity-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapBuilderRoute = RoadmapBuilderRouteImport.update({
  id: '/roadmap-builder',
  path: '/roadmap-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/opportunity-details': typeof OpportunityDetailsRoute
  '/paths': typeof PathsRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap-builder': typeof RoadmapBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/opportunity-details': typeof OpportunityDetailsRoute
  '/paths': typeof PathsRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap-builder': typeof RoadmapBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/opportunity-details': typeof OpportunityDetailsRoute
  '/paths': typeof PathsRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/roadmap-builder': typeof RoadmapBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/opportunities'
    | '/opportunity-details'
    | '/paths'
    | '/pin'
    | '/profile'
    | '/progress'
    | '/roadmap-builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/opportunities'
    | '/opportunity-details'
    | '/paths'
    | '/pin'
    | '/profile'
    | '/progress'
    | '/roadmap-builder'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/opportunities'
    | '/opportunity-details'
    | '/paths'
    | '/pin'
    | '/profile'
    | '/progress'
    | '/roadmap-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OpportunityDetailsRoute: typeof OpportunityDetailsRoute
  PathsRoute: typeof PathsRoute
  PinRoute: typeof PinRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RoadmapBuilderRoute: typeof RoadmapBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-details': {
      id: '/opportunity-details'
      path: '/opportunity-details'
      fullPath: '/opportunity-details'
      preLoaderRoute: typeof OpportunityDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap-builder': {
      id: '/roadmap-builder'
      path: '/roadmap-builder'
      fullPath: '/roadmap-builder'
      preLoaderRoute: typeof RoadmapBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OpportunityDetailsRoute: OpportunityDetailsRoute,
  PathsRoute: PathsRoute,
  PinRoute: PinRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RoadmapBuilderRoute: RoadmapBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
